export const BASE_URL = "http://localhost:8080"
export const CART_KEY = "com.walydscommerce/cart"
export const TOKEN_KEY = "com.waly.dscommerce/token"
export const CLIENT_ID = "myclientid"
export const CLIENT_SECRET = "myclientsecret"